
insert into locations(name, pincode, description, city) values
('Crest Line', '83594', 'Versatile holistic secured line', 'Gudong'),
('Dayton', '85830', 'Expanded web-enabled core', 'Nice'),
('Oak', '7', 'Grass-roots radical paradigm', 'Damao'),
('Commercial', '10', 'Multi-layered exuding help-desk', 'Shiqiao'),
('Lunder', '4', 'Optimized directional monitoring', 'Piterka'),
('Spohn', '52', 'Expanded foreground workforce', 'Anle'),
('Atwood', '8771', 'Balanced foreground software', 'Buenos Aires'),
('Maple Wood', '36289', 'Visionary directional software', 'Taishang'),
('Arapahoe', '46584', 'Progressive client-server extranet', 'Marseille'),
('Artisan', '7', 'Digitized empowering structure', 'Porangaba'),
('Declaration', '7', 'Customer-focused optimal ability', 'San Miguel'),
('Maple Wood', '0932', 'Configurable zero defect encoding', 'Palestina'),
('1st', '0021', 'Visionary coherent website', 'Al Ḩāḑir'),
('Rieder', '3', 'Synchronised global superstructure', 'Saparua'),
('Fulton', '68', 'Synergized cohesive middleware', 'Sinegor''ye'),
('Debs', '898', 'Enterprise-wide actuating matrix', 'Pacatuba'),
('Holmberg', '44', 'Fundamental radical hardware', 'Pingdingshan'),
('Messerschmidt', '6', 'Open-architected clear-thinking support', 'Viterbo'),
('Northwestern', '4926', 'Expanded 5th generation product', 'Flin Flon'),
('Roxbury', '4749', 'Synchronised bi-directional budgetary management', 'Bahui'),
('Stang', '8', 'Self-enabling reciprocal analyzer', 'Gračanica'),
('Rigney', '365', 'Programmable analyzing orchestration', 'Turiys’k'),
('Graceland', '94428', 'Networked zero administration support', 'Uyovu'),
('Bartillon', '540', 'Grass-roots human-resource alliance', 'Jagodina'),
('Charing Cross', '190', 'Advanced analyzing array', 'Capellanía'),
('Vahlen', '05', 'Open-architected multimedia collaboration', 'Torsby'),
('Acker', '5', 'Switchable motivating utilisation', 'Skhodnitsa'),
('Lunder', '508', 'Right-sized foreground extranet', 'Ozerki'),
('International', '47', 'Programmable object-oriented hub', 'Rennes'),
('Towne', '02', 'Business-focused empowering circuit', 'Hongzhou'),
('Mesta', '5129', 'Organized user-facing access', 'Cijayana'),
('Riverside', '098', 'Digitized intermediate customer loyalty', 'Xinhua'),
('Morning', '2', 'Proactive bottom-line open architecture', 'Gualeguay'),
('Daystar', '47', 'Organic local definition', 'Chahe'),
('Gale', '7', 'Switchable bi-directional leverage', 'Cololaca'),
('Daystar', '242', 'Enhanced motivating frame', 'Huaminglou'),
('Bultman', '77', 'Total optimal contingency', 'Guadalupe'),
('Pepper Wood', '1885', 'Fundamental fresh-thinking instruction set', 'Cradock'),
('Transport', '0', 'Diverse 3rd generation instruction set', 'Novohrad-Volyns’kyy'),
('Prentice', '0', 'Fundamental context-sensitive hub', 'Leiyang'),
('Novick', '754', 'Digitized tangible Graphical User Interface', 'Firenze'),
('4th', '3637', 'Multi-layered mobile project', 'Paris 09'),
('Merrick', '200', 'Balanced multi-state forecast', 'Banjar Taro Kelod'),
('Esch', '139', 'User-friendly demand-driven productivity', 'Pshekhskaya'),
('Lien', '38', 'Balanced non-volatile conglomeration', 'Bherāmāra'),
('Dixon', '4107', 'Mandatory tangible throughput', 'Emiliano Zapata'),
('Oxford', '0', 'Exclusive didactic methodology', 'Deje'),
('Hanover', '88', 'Open-architected human-resource concept', 'Jessore'),
('Scott', '1398', 'Synergized value-added help-desk', 'Chengyang'),
('Porter', '250', 'Cloned solution-oriented support', 'Yamen');
