create table product_list (
	name TEXT,
	avatar TEXT,
	description TEXT,
	address TEXT,
	meta JSONB
);


insert into product_list (name, avatar, description, address, meta) values ('Aqua Blue', 'https://media.mojoreads.com/bisleri.png', 'Intuitive systemic concept', '0640 Namekagon Court', '{"since":2005,"ISO Certified":true}'),
('Absopure', 'https://media.mojoreads.com/falcon.png', 'Adaptive 24 hour software', '210 Tomscot Plaza', '{"since":2005,"ISO Certified":true}'),
('Acadia (Niagra Bottling)', 'https://media.mojoreads.com/aquafina.png', 'Function-based explicit moratorium', '8754 Norway Maple Parkway', '{"since":2005,"ISO Certified":true}'),
('Acme (Niagra Bottling)', 'https://media.mojoreads.com/kelvin.png', 'Profit-focused solution-oriented project', '473 Debs Place', '{"since":2005,"ISO Certified":true}'),
('Al Ain Water', 'https://media.mojoreads.com/no_brand.png', 'Decentralized analyzing model', '006 Tony Center', '{"since":2005,"ISO Certified":true}'),
('Agua Mineral Salus', 'https://media.mojoreads.com/bisleri.png', 'Automated cohesive project', '1392 Weeping Birch Junction', '{"since":2005,"ISO Certified":true}'),
('Aglow', 'https://media.mojoreads.com/falcon.png', 'Object-based heuristic groupware', '071 Kinsman Crossing', '{"since":2005,"ISO Certified":true}'),
('Agua Vida', 'https://media.mojoreads.com/aquafina.png', 'Reactive optimizing knowledge user', '3172 Kim Lane', '{"since":2005,"ISO Certified":true}'),
('Alkalife TEN', 'https://media.mojoreads.com/kelvin.png', 'Configurable full-range interface', '13588 Farragut Way', '{"since":2005,"ISO Certified":true}'),
('Ambo Mineral Water', 'https://media.mojoreads.com/no_brand.png', 'Visionary client-driven analyzer', '35677 Kings Hill', '{"since":2005,"ISO Certified":true}'),
('Amma Kudineer', 'https://media.mojoreads.com/bisleri.png', 'Visionary coherent support', '56839 Columbus Junction', '{"since":2005,"ISO Certified":true}'),
('Antipodes Water Company', 'https://media.mojoreads.com/falcon.png', 'Upgradable well-modulated function', '5 Lake View Road', '{"since":2005,"ISO Certified":true}'),
('Apenta', 'https://media.mojoreads.com/aquafina.png', 'Balanced zero tolerance ability', '4353 School Circle', '{"since":2005,"ISO Certified":true}'),
('Aparan (water)', 'https://media.mojoreads.com/kelvin.png', 'Front-line human-resource infrastructure', '685 Hoepker Junction', '{"since":2005,"ISO Certified":true}'),
('Apollinaris (water)', 'https://media.mojoreads.com/no_brand.png', 'Face to face discrete matrices', '327 Armistice Terrace', '{"since":2005,"ISO Certified":true}'),
('Aqua Pura', 'https://media.mojoreads.com/bisleri.png', 'Cross-group bi-directional emulation', '90 Dottie Place', '{"since":2005,"ISO Certified":true}'),
('Aquafina', 'https://media.mojoreads.com/falcon.png', 'Triple-buffered asymmetric contingency', '67938 Hovde Avenue', '{"since":2005,"ISO Certified":true}'),
('Aquaterra', 'https://media.mojoreads.com/aquafina.png', 'Business-focused user-facing infrastructure', '2 Riverside Trail', '{"since":2005,"ISO Certified":true}'),
('Aquilline', 'https://media.mojoreads.com/kelvin.png', 'Networked tangible approach', '9927 Cascade Crossing', '{"since":2005,"ISO Certified":true}'),
('Aquas', 'https://media.mojoreads.com/no_brand.png', 'Ergonomic dynamic methodology', '9007 Delladonna Trail', '{"since":2005,"ISO Certified":true}'),
('Ararat (water)', 'https://media.mojoreads.com/bisleri.png', 'Progressive cohesive strategy', '15494 Meadow Valley Pass', '{"since":2005,"ISO Certified":true}'),
('Архыз Archyz', 'https://media.mojoreads.com/falcon.png', 'Synchronised secondary focus group', '113 Fieldstone Parkway', '{"since":2005,"ISO Certified":true}'),
('Arrowhead Water', 'https://media.mojoreads.com/aquafina.png', 'Function-based context-sensitive Graphic Interface', '47 Norway Maple Trail', '{"since":2005,"ISO Certified":true}'),
('Ayvaz Water', 'https://media.mojoreads.com/kelvin.png', 'Balanced directional workforce', '2739 Summer Ridge Parkway', '{"since":2005,"ISO Certified":true}'),
('Arwa (water)', 'https://media.mojoreads.com/no_brand.png', 'Future-proofed attitude-oriented policy', '17560 Harper Parkway', '{"since":2005,"ISO Certified":true}'),
('Arzni (water)', 'https://media.mojoreads.com/bisleri.png', 'Persistent incremental data-warehouse', '94808 Eggendart Trail', '{"since":2005,"ISO Certified":true}'),
('Badoit', 'https://media.mojoreads.com/falcon.png', 'Expanded client-driven concept', '05284 4th Road', '{"since":2005,"ISO Certified":true}'),
('Ballygowan', 'https://media.mojoreads.com/aquafina.png', 'Adaptive upward-trending throughput', '9 Katie Drive', '{"since":2005,"ISO Certified":true}'),
('Bear-lithia', 'https://media.mojoreads.com/kelvin.png', 'Centralized even-keeled forecast', '16190 Bonner Hill', '{"since":2005,"ISO Certified":true}'),
('Belu (company)', 'https://media.mojoreads.com/no_brand.png', 'Optional background help-desk', '539 Dennis Place', '{"since":2005,"ISO Certified":true}'),
('Best Yet (Niagra Bottling)', 'https://media.mojoreads.com/bisleri.png', 'User-friendly interactive policy', '275 Burrows Parkway', '{"since":2005,"ISO Certified":true}'),
('Bjni (water)', 'https://media.mojoreads.com/falcon.png', 'Cloned bandwidth-monitored adapter', '8 Surrey Avenue', '{"since":2005,"ISO Certified":true}'),
('Big Y (Niagra Bottling)', 'https://media.mojoreads.com/aquafina.png', 'Future-proofed exuding toolset', '29727 Almo Road', '{"since":2005,"ISO Certified":true}'),
('Bílinská kyselka', 'https://media.mojoreads.com/kelvin.png', 'Robust static capacity', '9 Algoma Place', '{"since":2005,"ISO Certified":true}'),
('Bisleri', 'https://media.mojoreads.com/no_brand.png', 'Extended value-added hardware', '617 Kenwood Parkway', '{"since":2005,"ISO Certified":true}'),
('Bling H2O', 'https://media.mojoreads.com/bisleri.png', 'Secured clear-thinking open architecture', '45868 Comanche Hill', '{"since":2005,"ISO Certified":true}'),
('Blk. (water)', 'https://media.mojoreads.com/falcon.png', 'Re-contextualized client-server neural-net', '79524 Browning Street', '{"since":2005,"ISO Certified":true}'),
('Borjomi (water)', 'https://media.mojoreads.com/aquafina.png', 'Multi-channelled secondary open system', '2 Commercial Plaza', '{"since":2005,"ISO Certified":true}'),
('Brecon Carreg', 'https://media.mojoreads.com/kelvin.png', 'Reactive intermediate model', '13242 High Crossing Avenue', '{"since":2005,"ISO Certified":true}'),
('Buxton (UK)', 'https://media.mojoreads.com/no_brand.png', 'Distributed static implementation', '8092 Lakewood Gardens Drive', '{"since":2005,"ISO Certified":true}'),
('Byuregh (water)', 'https://media.mojoreads.com/bisleri.png', 'Expanded mission-critical contingency', '0289 Miller Junction', '{"since":2005,"ISO Certified":true}'),
('Ciel (beverage)', 'https://media.mojoreads.com/falcon.png', 'Multi-layered human-resource frame', '4900 Transport Crossing', '{"since":2005,"ISO Certified":true}'),
('Hiram Codd', 'https://media.mojoreads.com/aquafina.png', 'Inverse clear-thinking middleware', '41 Shopko Plaza', '{"since":2005,"ISO Certified":true}'),
('Cheddar Natural Spring Water', 'https://media.mojoreads.com/kelvin.png', 'Persistent scalable intranet', '4693 Shelley Alley', '{"since":2005,"ISO Certified":true}'),
('Contrex', 'https://media.mojoreads.com/no_brand.png', 'De-engineered bottom-line access', '14487 Cody Hill', '{"since":2005,"ISO Certified":true}'),
('Cool Ridge', 'https://media.mojoreads.com/bisleri.png', 'Grass-roots foreground matrix', '900 Manley Way', '{"since":2005,"ISO Certified":true}'),
('Crystal Clear (company)', 'https://media.mojoreads.com/falcon.png', 'Exclusive demand-driven policy', '2 Service Place', '{"since":2005,"ISO Certified":true}'),
('Crystal Geyser Water Company', 'https://media.mojoreads.com/aquafina.png', 'Re-contextualized grid-enabled secured line', '9 Moulton Terrace', '{"since":2005,"ISO Certified":true}'),
('Cyon Table water', 'https://media.mojoreads.com/kelvin.png', 'Operative multi-tasking collaboration', '554 Kim Crossing', '{"since":2005,"ISO Certified":true}'),
('Culligan', 'https://media.mojoreads.com/no_brand.png', 'Sharable neutral projection', '7813 5th Center', '{"since":2005,"ISO Certified":true}'),
('Damavand Mineral Water', 'https://media.mojoreads.com/bisleri.png', 'Ameliorated 4th generation capacity', '48 Texas Hill', '{"since":2005,"ISO Certified":true}'),
('Dana (Mirna)', 'https://media.mojoreads.com/falcon.png', 'Open-architected multi-state database', '0352 Prentice Pass', '{"since":2005,"ISO Certified":true}'),
('Dasani', 'https://media.mojoreads.com/aquafina.png', 'Multi-channelled national concept', '6859 Butterfield Court', '{"since":2005,"ISO Certified":true}'),
('Deep River Rock', 'https://media.mojoreads.com/kelvin.png', 'Enhanced bottom-line contingency', '25 Monument Avenue', '{"since":2005,"ISO Certified":true}'),
('Deep Spring (beverage brand)', 'https://media.mojoreads.com/no_brand.png', 'Devolved 5th generation support', '0184 Welch Alley', '{"since":2005,"ISO Certified":true}'),
('Deer Park Spring Water', 'https://media.mojoreads.com/bisleri.png', 'Horizontal hybrid product', '43947 Rusk Pass', '{"since":2005,"ISO Certified":true}'),
('Decantae (UK)', 'https://media.mojoreads.com/falcon.png', 'Robust real-time instruction set', '2409 Summit Terrace', '{"since":2005,"ISO Certified":true}'),
('Dilijan (water)', 'https://media.mojoreads.com/aquafina.png', 'Ameliorated optimal array', '2183 Main Center', '{"since":2005,"ISO Certified":true}'),
('Dejà Blue', 'https://media.mojoreads.com/kelvin.png', 'Front-line holistic access', '1 Coleman Trail', '{"since":2005,"ISO Certified":true}'),
('Donat Mg', 'https://media.mojoreads.com/no_brand.png', 'Future-proofed fresh-thinking algorithm', '5 Fair Oaks Point', '{"since":2005,"ISO Certified":true}'),
('Drench', 'https://media.mojoreads.com/bisleri.png', 'Up-sized attitude-oriented orchestration', '73 Truax Alley', '{"since":2005,"ISO Certified":true}'),
('Drink More Water', 'https://media.mojoreads.com/falcon.png', 'Enhanced high-level database', '17 Bartillon Drive', '{"since":2005,"ISO Certified":true}'),
('Earth Water', 'https://media.mojoreads.com/aquafina.png', 'Virtual user-facing access', '085 Straubel Hill', '{"since":2005,"ISO Certified":true}'),
('Eden Springs', 'https://media.mojoreads.com/kelvin.png', 'Persevering national task-force', '58 Cody Point', '{"since":2005,"ISO Certified":true}'),
('Ein Gedi Mineral Water', 'https://media.mojoreads.com/no_brand.png', 'Optional mission-critical archive', '58045 Myrtle Avenue', '{"since":2005,"ISO Certified":true}'),
('Energy Brands', 'https://media.mojoreads.com/bisleri.png', 'Switchable reciprocal moratorium', '77 Elmside Plaza', '{"since":2005,"ISO Certified":true}'),
('Ессентуки Essentuki №4, №17', 'https://media.mojoreads.com/falcon.png', 'Centralized explicit matrix', '1 Vidon Court', '{"since":2005,"ISO Certified":true}'),
('Ethos Water', 'https://media.mojoreads.com/aquafina.png', 'Optimized bottom-line workforce', '20686 American Ash Pass', '{"since":2005,"ISO Certified":true}'),
('Evian', 'https://media.mojoreads.com/kelvin.png', 'Customer-focused object-oriented methodology', '138 Donald Place', '{"since":2005,"ISO Certified":true}'),
('Jermuk (water)', 'https://media.mojoreads.com/no_brand.png', 'Streamlined stable matrices', '97526 Riverside Park', '{"since":2005,"ISO Certified":true}'),
('Hayler Water', 'https://media.mojoreads.com/bisleri.png', 'Visionary background approach', '30 Mendota Circle', '{"since":2005,"ISO Certified":true}'),
('Highland Spring (UK)', 'https://media.mojoreads.com/falcon.png', 'Integrated full-range product', '7 Elmside Court', '{"since":2005,"ISO Certified":true}'),
('Staatl. Fachingen', 'https://media.mojoreads.com/aquafina.png', 'Distributed radical interface', '91 Drewry Plaza', '{"since":2005,"ISO Certified":true}'),
('Farris (mineral water)', 'https://media.mojoreads.com/kelvin.png', 'Customizable coherent intranet', '269 Larry Circle', '{"since":2005,"ISO Certified":true}'),
('Fiji Water', 'https://media.mojoreads.com/no_brand.png', 'Self-enabling modular frame', '871 Chinook Lane', '{"since":2005,"ISO Certified":true}'),
('FRED Water http://www.fredwater.com', 'https://media.mojoreads.com/bisleri.png', 'Multi-tiered transitional frame', '796 Annamark Street', '{"since":2005,"ISO Certified":true}'),
('Fruit2O', 'https://media.mojoreads.com/falcon.png', 'Object-based analyzing internet solution', '17 Heffernan Center', '{"since":2005,"ISO Certified":true}'),
('Fuentealta', 'https://media.mojoreads.com/aquafina.png', 'Open-source executive alliance', '5 Kennedy Alley', '{"since":2005,"ISO Certified":true}'),
('Galvanina', 'https://media.mojoreads.com/kelvin.png', 'Versatile 5th generation function', '89 Evergreen Point', '{"since":2005,"ISO Certified":true}'),
('Gasteiner/><', 'https://media.mojoreads.com/no_brand.png', 'Business-focused context-sensitive internet solution', '3261 Elgar Point', '{"since":2005,"ISO Certified":true}'),
('Garni (water)', 'https://media.mojoreads.com/bisleri.png', 'Self-enabling fresh-thinking protocol', '519 Riverside Pass', '{"since":2005,"ISO Certified":true}'),
('Gerolsteiner Brunnen', 'https://media.mojoreads.com/falcon.png', 'Down-sized fault-tolerant extranet', '8 Hollow Ridge Avenue', '{"since":2005,"ISO Certified":true}'),
('Glaceau', 'https://media.mojoreads.com/aquafina.png', 'Multi-tiered directional infrastructure', '0 Mallory Terrace', '{"since":2005,"ISO Certified":true}'),
('Great Value', 'https://media.mojoreads.com/kelvin.png', 'Reactive methodical flexibility', '9 Rowland Terrace', '{"since":2005,"ISO Certified":true}'),
('Gourmet Foods', 'https://media.mojoreads.com/no_brand.png', 'Reverse-engineered content-based methodology', '4 Anhalt Park', '{"since":2005,"ISO Certified":true}'),
('Harrogate Spa Water', 'https://media.mojoreads.com/bisleri.png', 'Re-contextualized holistic framework', '2295 Haas Circle', '{"since":2005,"ISO Certified":true}'),
('Hawaiian Springs Water', 'https://media.mojoreads.com/falcon.png', 'Business-focused contextually-based hardware', '510 Hauk Avenue', '{"since":2005,"ISO Certified":true}'),
('Highland Spring', 'https://media.mojoreads.com/aquafina.png', 'Inverse zero defect support', '1401 Lotheville Park', '{"since":2005,"ISO Certified":true}'),
('Himalaya', 'https://media.mojoreads.com/kelvin.png', 'Focused coherent paradigm', '6935 Doe Crossing Circle', '{"since":2005,"ISO Certified":true}'),
('Hope in a Bottle', 'https://media.mojoreads.com/no_brand.png', 'Re-engineered modular infrastructure', '4970 Lakewood Gardens Place', '{"since":2005,"ISO Certified":true}'),
('Ice Mountain (water)', 'https://media.mojoreads.com/bisleri.png', 'Monitored global core', '0186 Nevada Junction', '{"since":2005,"ISO Certified":true}'),
('Iceland Pure Spring Water', 'https://media.mojoreads.com/falcon.png', 'Reactive cohesive success', '573 Hollow Ridge Terrace', '{"since":2005,"ISO Certified":true}'),
('Iceland Spring', 'https://media.mojoreads.com/aquafina.png', 'Versatile client-driven help-desk', '1 Golden Leaf Pass', '{"since":2005,"ISO Certified":true}'),
('Icelandic Glacial', 'https://media.mojoreads.com/kelvin.png', 'Universal demand-driven database', '65 Pepper Wood Pass', '{"since":2005,"ISO Certified":true}'),
('Isklar', 'https://media.mojoreads.com/no_brand.png', 'Innovative fault-tolerant definition', '0570 Oak Junction', '{"since":2005,"ISO Certified":true}'),
('Jamnica (company)', 'https://media.mojoreads.com/bisleri.png', 'Visionary asymmetric extranet', '5 Superior Hill', '{"since":2005,"ISO Certified":true}'),
('Jana (brand)', 'https://media.mojoreads.com/falcon.png', 'Grass-roots empowering workforce', '2163 Merrick Junction', '{"since":2005,"ISO Certified":true}'),
('Jeema Water', 'https://media.mojoreads.com/aquafina.png', 'Advanced content-based implementation', '02 Messerschmidt Junction', '{"since":2005,"ISO Certified":true}'),
('Just Water', 'https://media.mojoreads.com/kelvin.png', 'Secured impactful productivity', '9001 Amoth Park', '{"since":2005,"ISO Certified":true}'),
('Knjaz Miloš a.d.', 'https://media.mojoreads.com/no_brand.png', 'Sharable asymmetric paradigm', '53246 Corscot Drive', '{"since":2005,"ISO Certified":true}'),
('Kruna Voda', 'https://media.mojoreads.com/bisleri.png', 'Extended actuating budgetary management', '07 Bultman Parkway', '{"since":2005,"ISO Certified":true}'),
('Lalpina', 'https://media.mojoreads.com/falcon.png', 'Monitored responsive alliance', '125 Crownhardt Alley', '{"since":2005,"ISO Certified":true}'),
('Lithia (water brand)', 'https://media.mojoreads.com/aquafina.png', 'Stand-alone optimizing system engine', '9781 Brickson Park Avenue', '{"since":2005,"ISO Certified":true}'),
('Londonderry Lithia', 'https://media.mojoreads.com/kelvin.png', 'Open-architected attitude-oriented instruction set', '190 Sheridan Hill', '{"since":2005,"ISO Certified":true}'),
('Mai Dubai', 'https://media.mojoreads.com/no_brand.png', 'Multi-tiered hybrid core', '8 South Court', '{"since":2005,"ISO Certified":true}'),
('Malvern water', 'https://media.mojoreads.com/bisleri.png', 'Reverse-engineered 6th generation solution', '475 Express Pass', '{"since":2005,"ISO Certified":true}'),
('Malvern Water (bottled water)', 'https://media.mojoreads.com/falcon.png', 'Reverse-engineered upward-trending approach', '91 Corben Avenue', '{"since":2005,"ISO Certified":true}'),
('Mattoni', 'https://media.mojoreads.com/aquafina.png', 'Profit-focused clear-thinking circuit', '43 Everett Plaza', '{"since":2005,"ISO Certified":true}'),
('Mey Eden', 'https://media.mojoreads.com/kelvin.png', 'Vision-oriented leading edge extranet', '204 New Castle Park', '{"since":2005,"ISO Certified":true}'),
('Mohai Agnes mineral water', 'https://media.mojoreads.com/no_brand.png', 'Reduced motivating Graphic Interface', '74598 Village Parkway', '{"since":2005,"ISO Certified":true}'),
('Morning Fresh (Niagra Bottling)', 'https://media.mojoreads.com/bisleri.png', 'Networked tertiary hardware', '85616 Buena Vista Center', '{"since":2005,"ISO Certified":true}'),
('Mount Franklin Water', 'https://media.mojoreads.com/falcon.png', 'Synergized leading edge array', '84206 Shelley Place', '{"since":2005,"ISO Certified":true}'),
('Mountain Valley Spring Water', 'https://media.mojoreads.com/aquafina.png', 'Customer-focused systemic functionalities', '61 Dryden Place', '{"since":2005,"ISO Certified":true}'),
('Nabeglavi', 'https://media.mojoreads.com/kelvin.png', 'Compatible cohesive access', '1056 Luster Plaza', '{"since":2005,"ISO Certified":true}'),
('Нарзан Narzan', 'https://media.mojoreads.com/no_brand.png', 'Public-key exuding paradigm', '77 Cherokee Junction', '{"since":2005,"ISO Certified":true}'),
('Nantze Springs', 'https://media.mojoreads.com/bisleri.png', 'Proactive systemic contingency', '2802 Arizona Alley', '{"since":2005,"ISO Certified":true}'),
('Naya Waters', 'https://media.mojoreads.com/falcon.png', 'Cross-platform attitude-oriented middleware', '1 Village Court', '{"since":2005,"ISO Certified":true}'),
('Nera Kritis', 'https://media.mojoreads.com/aquafina.png', 'Profit-focused eco-centric encoding', '1 Carberry Junction', '{"since":2005,"ISO Certified":true}'),
('Nestlé Pure Life', 'https://media.mojoreads.com/kelvin.png', 'Stand-alone attitude-oriented middleware', '4546 Badeau Point', '{"since":2005,"ISO Certified":true}'),
('NEPTUNE نپتون', 'https://media.mojoreads.com/no_brand.png', 'Fully-configurable 24/7 hardware', '61121 Walton Crossing', '{"since":2005,"ISO Certified":true}'),
('Nestlé Waters', 'https://media.mojoreads.com/bisleri.png', 'Secured context-sensitive matrices', '02 Farragut Avenue', '{"since":2005,"ISO Certified":true}'),
('Nestlé Waters North America', 'https://media.mojoreads.com/falcon.png', 'Synergistic stable time-frame', '7 Carey Avenue', '{"since":2005,"ISO Certified":true}'),
('Nice aqua', 'https://media.mojoreads.com/aquafina.png', 'Synergized uniform monitoring', '2574 Eastwood Avenue', '{"since":2005,"ISO Certified":true}'),
('NEWater', 'https://media.mojoreads.com/kelvin.png', 'Reverse-engineered static contingency', '5430 Burning Wood Park', '{"since":2005,"ISO Certified":true}'),
('Niagra (Niagra Bottling)', 'https://media.mojoreads.com/no_brand.png', 'De-engineered tertiary data-warehouse', '62767 3rd Place', '{"since":2005,"ISO Certified":true}'),
('Nongfu Spring', 'https://media.mojoreads.com/bisleri.png', 'Decentralized empowering analyzer', '9 Spohn Pass', '{"since":2005,"ISO Certified":true}'),
('Noy (water)', 'https://media.mojoreads.com/falcon.png', 'Triple-buffered responsive solution', '0564 Clove Alley', '{"since":2005,"ISO Certified":true}'),
('Нурлы Nurli water', 'https://media.mojoreads.com/aquafina.png', 'Right-sized reciprocal focus group', '90 Carberry Plaza', '{"since":2005,"ISO Certified":true}'),
('ORIZON', 'https://media.mojoreads.com/kelvin.png', 'Reactive hybrid core', '3583 Nelson Trail', '{"since":2005,"ISO Certified":true}'),
('ORO LUXURY WATER', 'https://media.mojoreads.com/no_brand.png', 'Decentralized modular local area network', '98 Pepper Wood Hill', '{"since":2005,"ISO Certified":true}'),
('Ошмес Oshmes', 'https://media.mojoreads.com/bisleri.png', 'Fully-configurable non-volatile initiative', '28566 Rutledge Avenue', '{"since":2005,"ISO Certified":true}'),
('Ozarka', 'https://media.mojoreads.com/falcon.png', 'Multi-tiered actuating challenge', '8864 Morningstar Way', '{"since":2005,"ISO Certified":true}'),
('Panama Blue', 'https://media.mojoreads.com/aquafina.png', 'Switchable systemic toolset', '56 Sunnyside Street', '{"since":2005,"ISO Certified":true}'),
('Panna (water)', 'https://media.mojoreads.com/kelvin.png', 'Cross-group clear-thinking process improvement', '417 Arkansas Junction', '{"since":2005,"ISO Certified":true}'),
('Pennine Spring', 'https://media.mojoreads.com/no_brand.png', 'Object-based contextually-based local area network', '1002 Drewry Crossing', '{"since":2005,"ISO Certified":true}'),
('Penta Water', 'https://media.mojoreads.com/bisleri.png', 'Profit-focused reciprocal paradigm', '115 Schmedeman Road', '{"since":2005,"ISO Certified":true}'),
('Perrier', 'https://media.mojoreads.com/falcon.png', 'Stand-alone eco-centric toolset', '484 Magdeline Alley', '{"since":2005,"ISO Certified":true}'),
('Persa (water)', 'https://media.mojoreads.com/aquafina.png', 'Decentralized cohesive focus group', '4 Ridge Oak Parkway', '{"since":2005,"ISO Certified":true}'),
('Pluto Water', 'https://media.mojoreads.com/kelvin.png', 'Organized intangible local area network', '1043 Forster Court', '{"since":2005,"ISO Certified":true}'),
('Poland Spring', 'https://media.mojoreads.com/no_brand.png', 'Digitized dynamic monitoring', '71 Autumn Leaf Circle', '{"since":2005,"ISO Certified":true}'),
('Powwow Water', 'https://media.mojoreads.com/bisleri.png', 'Multi-layered zero administration application', '347 Talmadge Plaza', '{"since":2005,"ISO Certified":true}'),
('Pricerite (Niagra Bottling)', 'https://media.mojoreads.com/falcon.png', 'Exclusive eco-centric approach', '1291 Vermont Way', '{"since":2005,"ISO Certified":true}'),
('Princes Gate Spring Water', 'https://media.mojoreads.com/aquafina.png', 'Versatile didactic array', '3216 Springs Junction', '{"since":2005,"ISO Certified":true}'),
('Propel Fitness Water', 'https://media.mojoreads.com/kelvin.png', 'Face to face reciprocal data-warehouse', '14377 Acker Avenue', '{"since":2005,"ISO Certified":true}'),
('Pump (Water)', 'https://media.mojoreads.com/no_brand.png', 'Mandatory next generation open system', '2 Barnett Court', '{"since":2005,"ISO Certified":true}'),
('PurBlu Beverages, Inc', 'https://media.mojoreads.com/bisleri.png', 'Up-sized responsive architecture', '46220 Pankratz Court', '{"since":2005,"ISO Certified":true}'),
('Radenska', 'https://media.mojoreads.com/falcon.png', 'Profit-focused 6th generation matrices', '78554 Hoffman Park', '{"since":2005,"ISO Certified":true}'),
('Alkaline Drink', 'https://media.mojoreads.com/aquafina.png', 'Down-sized needs-based productivity', '49 Granby Way', '{"since":2005,"ISO Certified":true}'),
('Riviere water', 'https://media.mojoreads.com/kelvin.png', 'Compatible even-keeled framework', '96 Montana Lane', '{"since":2005,"ISO Certified":true}'),
('Ramlösa', 'https://media.mojoreads.com/no_brand.png', 'Networked solution-oriented knowledge base', '25044 Ridge Oak Place', '{"since":2005,"ISO Certified":true}');
