# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      - image: google/cloud-sdk
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: inventory_test
          POSTGRES_PASSWORD: postgres

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - setup_remote_docker
      - run:
          name: Configure and build images to deploy to GKE
          command: |
            echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update kubectl
            sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

            docker build -t gcr.io/${GOOGLE_PROJECT_ID}/inventory:build-$CIRCLE_BUILD_NUM .
            # Using a separate tag command until Docker 1.10 is available on CircleCI, then we can use two tags in the build command above
            docker tag gcr.io/${GOOGLE_PROJECT_ID}/inventory:build-$CIRCLE_BUILD_NUM gcr.io/${GOOGLE_PROJECT_ID}/inventory:latest
      - deploy:
          name: Deploy to GKE
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy_prod.sh
            fi




