CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255),
  description VARCHAR(255) NOT NULL,
  capacity INTEGER DEFAULT 20 NOT NULL,
  meta JSONB NOT NULL,
  address VARCHAR(255) NOT NULL,
  "verifiedAt" TIMESTAMP WITH TIME ZONE,
  "verifiedBy" VARCHAR(255),
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL
);
