CREATE TABLE "orderItems" (
  id SERIAL PRIMARY KEY,
  "sellerId" INTEGER NOT NULL,
  "productId" INTEGER NOT NULL,
  "orderId" INTEGER NOT NULL,
  status VARCHAR(255),
  quantity INTEGER DEFAULT 16 NOT NULL,
  price INTEGER NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL
);
